dims: [48, 96, 192, 384]
num_res_blocks: [3, 3, 9, 3]
name: conv_vit_tiny
vit_equivalency: tiny
physics_aware: false
field_aware_stem: null
periodic_padding: null
temporal_downsample_start_stage: null
use_global_context_token: false
field_group_sizes: null
